-- NETLINK: учёт трафика и лимит на подписчика.
-- Лимит общий для Premium и «Ускоренного интернета»: по части соединения
-- это одна и та же услуга.
ALTER TABLE "VpnSettings" ADD COLUMN IF NOT EXISTS "trafficLimitGb" INTEGER NOT NULL DEFAULT 250;
ALTER TABLE "VpnSettings" ADD COLUMN IF NOT EXISTS "usagePeriodDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "VpnSettings" ADD COLUMN IF NOT EXISTS "overLimitAction" TEXT NOT NULL DEFAULT 'BLOCK';
ALTER TABLE "VpnSettings" ADD COLUMN IF NOT EXISTS "throttleKbps" INTEGER NOT NULL DEFAULT 2048;

ALTER TABLE "VpnPeer" ADD COLUMN IF NOT EXISTS "rxBytes" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "VpnPeer" ADD COLUMN IF NOT EXISTS "txBytes" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "VpnPeer" ADD COLUMN IF NOT EXISTS "lastRx" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "VpnPeer" ADD COLUMN IF NOT EXISTS "lastTx" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "VpnPeer" ADD COLUMN IF NOT EXISTS "usageResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
